'use client';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import BrandLogo from './BrandLogo';
import RetroWindow from './RetroWindow';
import AdminTabs from './AdminTabs';
import DebugTable from './DebugTable';
import LogViewer from './LogViewer';
import { api, money } from '@/lib/api';
import type { Result, Plan, Zone } from '@/lib/types';
type Json = Record<string, unknown>;
type Snapshot = Result & { frames: Record<string, Json>; human_preview: string; source_map: Record<string,string>; jev_preview: Json; config_snapshot: Json; classic_pivots: Json };
const asRows=(value:unknown):Json[]=>Array.isArray(value)?value:[];
function JsonView({ value }: { value:unknown }) {return <pre>{JSON.stringify(value,null,2)}</pre>;}
function Copy({ value }: { value:unknown }) {const [state,setState]=useState('COPY JSON');return <button onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(value,null,2));setState('COPIED');}catch{setState('COPY FAILED');}setTimeout(()=>setState('COPY JSON'),2000);}}>{state}</button>;}
function Horizon(){const [days,setDays]=useState('7'),[plan,setPlan]=useState<Plan|null>(null),[error,setError]=useState('');useEffect(()=>{api<Plan>(`/admin/horizon?days=${days}`).then(setPlan).catch(e=>setError(e.message));},[days]);return <><label className="field">REQUESTED HORIZON<select value={days} onChange={e=>setDays(e.target.value)}>{[1,3,7,14,30].map(d=><option key={d} value={d}>{d} DAYS</option>)}</select></label>{error&&<p>{error}</p>}{plan&&<><div className="admin-status-grid">{[['PRIMARY',plan.primary_timeframe],['SECONDARY',plan.secondary_timeframe],['CONTEXT',plan.context_timeframe]].map(([k,v])=><div className="admin-stat" key={k}><span>{k}</span><strong>{v.toUpperCase()}</strong></div>)}</div><DebugTable rows={Object.entries(plan.timeframe_weights).map(([timeframe,weight])=>({timeframe,weight}))}/><p>Holding period determines the horizon. If omitted, max(1 day, action timing) is used. All configured weights sum to 1.</p></>}</>;}
export default function AdminDesktop(){
 const router=useRouter();const [authenticated,setAuthenticated]=useState(false),[tab,setTab]=useState('OVERVIEW'),[tf,setTf]=useState('4h'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[health,setHealth]=useState<Json>({}),[raw,setRaw]=useState<Json|null>(null),[system,setSystem]=useState<Json>({}),[history,setHistory]=useState<Json[]>([]),[historyOffset,setHistoryOffset]=useState(0),[view,setView]=useState('READABLE');
 useEffect(()=>{api('/admin/me').then(()=>setAuthenticated(true)).catch(()=>router.replace('/admin/login'));},[router]);
 const loadLatest=useCallback(async()=>{try{setSnapshot(await api<Snapshot>('/admin/analysis/latest'));}catch(e){if(!(e as Error).message.startsWith('No analysis'))setError((e as Error).message);}},[]);
 useEffect(()=>{if(!authenticated)return;void loadLatest();api<Json>('/health').then(setHealth).catch(e=>setError(e.message));api<Json>('/admin/system').then(setSystem).catch(e=>setError(e.message));},[authenticated,loadLatest]);
 const loadRaw=useCallback(async(refresh=false)=>{setBusy(true);setError('');setRaw(null);try{setRaw(await api<Json>(`/admin/raw?timeframe=${tf}&refresh=${refresh}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[tf]);
 useEffect(()=>{if(authenticated&&tab==='RAW.DATA')void loadRaw();},[authenticated,tab,loadRaw]);
 useEffect(()=>{if(authenticated&&tab==='HISTORY')api<Json[]>(`/admin/history?offset=${historyOffset}`).then(setHistory).catch(e=>setError(e.message));},[authenticated,tab,historyOffset]);
 if(!authenticated)return <main className="login-page"><RetroWindow title="ADMIN.AUTH"><p>CHECKING.SESSION…</p></RetroWindow></main>;
 const c=snapshot?.context, frame=snapshot?.frames[tf];
 const needsAnalysis=['INDICATORS','PRICE.ACTION','S/R','DECISION.CONTEXT','JEV.PREVIEW'].includes(tab);
 return <main className="admin-page"><header className="admin-header"><BrandLogo/><div><span className="outline-tag">JEV DISABLED</span><a href="/">PUBLIC APP ↗</a><button onClick={async()=>{try{await api('/admin/logout',{method:'POST',body:'{}'});router.replace('/admin/login');}catch(e){setError((e as Error).message);}}}>LOG OUT</button></div></header><div className="admin-layout"><AdminTabs active={tab} onChange={t=>{setTab(t);setError('');}}/><div className="admin-content"><RetroWindow title={`ADMIN.${tab}`} status="INSPECTION WORKSPACE">
 {error&&<div role="alert" className="inline-error">{error}</div>}
 {snapshot&&<div className="admin-selected">ANALYSIS {snapshot.analysis_id} · {new Date(snapshot.timestamp).toLocaleString()} · v{snapshot.engine_version} <button onClick={()=>void loadLatest()}>LOAD LATEST</button></div>}
 {['RAW.DATA','INDICATORS','PRICE.ACTION','S/R'].includes(tab)&&<div className="admin-tools"><label>TIMEFRAME<select value={tf} onChange={e=>setTf(e.target.value)}>{['15m','1h','4h','1d','1w'].map(t=><option key={t} value={t}>{t.toUpperCase()}</option>)}</select></label>{tab==='RAW.DATA'&&<button disabled={busy} onClick={()=>void loadRaw(true)}>{busy?'FETCHING…':'REFRESH'}</button>}</div>}
 {needsAnalysis&&!snapshot?<div className="empty-admin"><h3>NO ANALYSIS YET</h3><p>Submit a plan on the public page, then load the saved calculations here.</p><a href="/">OPEN PUBLIC APP ↗</a><p><button onClick={()=>void loadLatest()}>LOAD LATEST</button></p></div>:<>
 {tab==='OVERVIEW'&&<><div className="admin-status-grid">{[['BINANCE',health.binance],['BACKEND',health.backend],['DATABASE',health.database],['ANALYSIS ENGINE',health.analysis_engine],['JEV','DISABLED'],['REFERENCE BTC PRICE',c?money(c.current_price):'NO ANALYSIS']].map(([key,value])=><div className="admin-stat" key={String(key)}><span>{String(key)}</span><strong>{String(value||'UNKNOWN')}</strong></div>)}</div><h3>DATA SNAPSHOT</h3><DebugTable rows={Object.entries((health.candle_counts||{}) as Json).map(([timeframe,count])=>({timeframe,candles:count}))}/><p>LAST DATA FETCH: {health.last_data_fetch?new Date(Number(health.last_data_fetch)).toLocaleString():'NOT FETCHED'}</p><p>LAST ANALYSIS: {snapshot?.timestamp||'NONE'}</p><p>Inspect live raw data in RAW.DATA. Run the public form to create a reproducible analysis record.</p><button onClick={()=>{api<Json>('/health').then(setHealth).catch(e=>setError(e.message));void loadLatest();}}>REFRESH OVERVIEW</button></>}
 {tab==='RAW.DATA'&&<>{busy?<p>FETCHING.BINANCE.DATA…</p>:raw&&<><div className="admin-tools"><Copy value={raw}/><span>BINANCE SPOT · {new Date(Number(raw.fetched_at)).toLocaleString()} · SHOWING LAST 50 / {asRows(raw.candles).length}</span></div><h3>NORMALIZED CANDLES</h3><DebugTable rows={asRows(raw.candles).slice(-50).reverse()}/><h3>RAW BINANCE ARRAYS</h3><JsonView value={Array.isArray(raw.raw)?raw.raw.slice(-20):raw.raw}/><p>UTC milliseconds. Open candles are visible here but excluded from all technical calculations.</p></>}</>}
 {tab==='INDICATORS'&&<>{frame?<><h3>{tf.toUpperCase()} / CLOSED-CANDLE INPUTS</h3><DebugTable rows={Object.entries((frame.indicators||{}) as Json).map(([metric,value])=>({metric,value}))}/><h3>VOLUME</h3><JsonView value={frame.volume}/><h3>VOLATILITY</h3><JsonView value={frame.volatility}/></>:<p>TIMEFRAME MISSING IN THIS ANALYSIS</p>}</>}
 {tab==='PRICE.ACTION'&&<>{frame?<><h3>MAJOR STRUCTURE</h3><JsonView value={frame.structure}/><h3>SHORT PIVOTS / 5 LEFT + 5 RIGHT</h3><DebugTable rows={asRows(frame.short_pivots)}/><h3>MAJOR PIVOTS / 20 LEFT + 20 RIGHT</h3><DebugTable rows={asRows(frame.major_pivots)}/><h3>BREAKOUTS / REJECTIONS</h3><JsonView value={frame.price_action}/><h3>PRIOR COMPLETED DAILY CLASSIC PIVOTS</h3><JsonView value={snapshot?.classic_pivots}/></>:<p>TIMEFRAME MISSING IN THIS ANALYSIS</p>}</>}
 {tab==='S/R'&&<>{frame?<><p>Cluster tolerance = ATR14 × 0.25. Consecutive intersecting candles count as one touch episode. Strength is the sum of the five component scores below.</p><div className="sr-cards">{(frame.zones as (Zone & Json)[]).map((z,i)=><article className="sr-card" key={i}><span className="eyebrow">{z.zone_type.toUpperCase()} · {z.major?'MAJOR':'SHORT'}</span><strong>{money(z.low)} — {money(z.high)}</strong><dl>{Object.entries(z).filter(([k])=>!['breakdown','low','high','zone_type'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl><DebugTable rows={Object.entries(z.breakdown).map(([component,score])=>({component,score}))}/><b>TOTAL {z.strength}/100</b></article>)}</div></>:<p>TIMEFRAME MISSING IN THIS ANALYSIS</p>}</>}
 {tab==='HORIZON'&&<><Horizon/>{snapshot&&<><h3>SELECTED ANALYSIS ALIGNMENT MATH</h3><JsonView value={snapshot.alignment}/></>}</>}
 {tab==='DECISION.CONTEXT'&&snapshot&&<><div className="admin-tabs-inline">{['READABLE','JSON','SOURCE MAP'].map(v=><button className={view===v?'active':''} key={v} onClick={()=>setView(v)}>{v}</button>)}<Copy value={c}/></div>{view==='READABLE'?<pre className="readable">{snapshot.human_preview}</pre>:view==='JSON'?<JsonView value={c}/>:<DebugTable rows={Object.entries(snapshot.source_map).map(([field,source])=>({field,source}))}/>}</>}
 {tab==='JEV.PREVIEW'&&snapshot&&<><div className="notice"><strong>JEV DISABLED — JEV REQUEST NOT SENT</strong><p>Local request draft for inspection. No external API is called. The live TypeSafe request contract remains unverified.</p></div><div className="admin-status-grid">{['model','character_count','approximate_token_count'].map(k=><div className="admin-stat" key={k}><span>{k.replaceAll('_',' ').toUpperCase()}</span><strong>{String(snapshot.jev_preview[k])}</strong></div>)}</div><Copy value={snapshot.jev_preview}/><details open><summary>GENERATED STATE & TYPED QUESTIONS</summary><JsonView value={snapshot.jev_preview.payload}/></details><details><summary>SERIALIZED REQUEST</summary><pre>{String(snapshot.jev_preview.serialized_request)}</pre></details></>}
 {tab==='HISTORY'&&<><div className="table-scroll"><table><thead><tr><th>Timestamp</th><th>Analysis ID</th><th>Intent</th><th>BTC price</th><th>Engine</th><th>Inspect</th></tr></thead><tbody>{history.map(row=><tr key={String(row.analysis_id)}><td>{String(row.timestamp)}</td><td>{String(row.analysis_id)}</td><td>{String((row.intent as Json).action)}</td><td>{money(Number(row.price))}</td><td>{String(row.engine_version)}</td><td><button onClick={async()=>{try{setSnapshot(await api<Snapshot>(`/admin/analysis/${row.analysis_id}`));setTab('DECISION.CONTEXT');}catch(e){setError((e as Error).message);}}}>OPEN</button></td></tr>)}</tbody></table></div>{!history.length&&<p>No saved analyses.</p>}<div className="admin-tools"><button disabled={historyOffset===0} onClick={()=>setHistoryOffset(Math.max(0,historyOffset-50))}>PREVIOUS</button><button disabled={history.length<50} onClick={()=>setHistoryOffset(historyOffset+50)}>NEXT</button></div></>}
 {tab==='LOGS'&&<LogViewer/>}
 {tab==='SYSTEM'&&<><p>Public market data only. Jev cannot be activated in this milestone.</p><JsonView value={system}/><h3>SELECTED ANALYSIS CONFIG SNAPSHOT</h3><JsonView value={snapshot?.config_snapshot||'No analysis selected'}/></>}
 </>}
 </RetroWindow></div></div></main>;
}
