import RetroWindow from './RetroWindow';
import { money, number } from '@/lib/api';
import type { Result, Zone } from '@/lib/types';
function Meter({ value }: { value: number }) {return <div className="meter"><span style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>;}
function ZoneView({ name, zone, price }: { name: string; zone: Zone | null; price: number }) {
 return <div className="zone-row"><span className="eyebrow">{name}</span><strong>{zone?`${money(zone.low)} — ${money(zone.high)}`:'NO CONFIRMED ZONE'}</strong>{zone?<><div className="stat-line"><span>STRENGTH {number(zone.strength,0)}/100</span><span>{number(Math.abs(zone.midpoint/price-1)*100)}% AWAY</span></div><Meter value={zone.strength}/></>:<p>Insufficient confirmed pivots near price.</p>}</div>;
}
export default function ResultPanels({ result }: { result: Result }) {
 const c=result.context, tf=c.analysis_plan.primary_timeframe, sr=c.support_resistance[tf], m=c.momentum[tf], v=c.volume[tf], vol=c.volatility[tf], ev=c.deterministic_evidence;
 return <div className="results" id="results">
  <RetroWindow title="ANALYSIS.RESULT" status={result.status}><div className="result-heading"><div><span className="eyebrow">CURRENT STRUCTURE / {tf.toUpperCase()}</span><h2>{c.market_structures[tf].state.toUpperCase()}<span className="outline-tag">{c.analysis_plan.requested_horizon_days} DAY HORIZON</span></h2><p>{c.user_intent.action.toUpperCase()} BTC · {c.user_intent.risk_profile.toUpperCase()} · ACT {c.user_intent.action_timing_days===0?'NOW':`WITHIN ${c.user_intent.action_timing_days} DAYS`}</p></div><div className="result-price"><span>ANALYSIS REFERENCE PRICE</span><strong>{money(c.current_price)}</strong></div></div>
   {result.missing_timeframes.length>0 && <p className="notice">PARTIAL DATA — missing: {result.missing_timeframes.join(', ')}. Missing alignment weights contribute uncertainty.</p>}
   <div className="structure-grid">{Object.entries(c.analysis_plan.timeframe_weights).map(([frame,weight])=><div key={frame}><span>{frame.toUpperCase()} <small>WEIGHT {number(weight*100,0)}%</small></span><strong>{c.market_structures[frame]?.state.toUpperCase()||'MISSING'}</strong></div>)}<div className="alignment"><span>ALIGNMENT</span><strong>{number(result.alignment.alignment_score,0)}<small>/100</small></strong><span>{result.alignment.alignment_direction.toUpperCase()}</span></div></div>
   <p className="source-note">{result.price_basis} · {new Date(result.timestamp).toLocaleString()}</p>
  </RetroWindow>
  <RetroWindow title="SCENARIOS & PLAN"><div className="guide-body"><h3>{result.alignment.alignment_direction==='mixed'?'Mixed evidence - wait for confirmation':`${result.alignment.alignment_direction.toUpperCase()} evidence leads across your horizon`}</h3><p>On {tf.toUpperCase()}, RSI is {number(m.rsi14,1)}, EMA20 is {m.ema20_slope}, and volume is {v.volume_ratio==null?'unavailable':`${number(v.volume_ratio)} times its previous average`}. {m.rsi14>70?'Momentum is extended to the upside; a pullback remains possible.':m.rsi14<30?'Momentum is extended to the downside; oversold does not guarantee a reversal.':'Momentum is outside the usual overbought and oversold extremes.'}</p><p><strong>Bullish scenario:</strong> {sr.nearest_resistance?`A ${tf} close above ${money(sr.nearest_resistance.high)}, followed by a successful retest and expanding volume, would strengthen upside evidence.`:'No confirmed resistance is available; a bullish trigger cannot be established.'}</p><p><strong>Bearish scenario:</strong> {sr.nearest_support?`A ${tf} close below ${money(sr.nearest_support.low)} would weaken support and strengthen downside evidence.`:'No confirmed support is available; a bearish trigger cannot be established.'}</p><p><strong>Range scenario:</strong> Price holding between support and resistance with weak volume favors continued indecision. These are conditional scenarios, not price targets.</p><p><strong>Your plan:</strong> {c.user_intent.action==='sell'?'For your planned exit, compare support failure with recovery above resistance.':c.user_intent.action==='hold'?'For your existing position, monitor structural invalidation and the distance to support.':c.user_intent.action==='wait'?'For a potential entry, watch a confirmed breakout or support retest.':'For a potential purchase, compare upside confirmation with the support-failure scenario.'} {c.user_intent.risk_profile==='conservative'?'Your conservative preference favors waiting for a closed-candle confirmation and retest.':c.user_intent.risk_profile==='aggressive'?'Earlier signals carry more false-breakout risk.':'Compare confirmation strength with the distance to invalidation.'} {c.user_intent.priority==='avoid_bad_entry'?'Check the distance to resistance before assessing entry quality.':c.user_intent.priority==='catch_trend_early'?'An early trend signal remains provisional until structure and volume confirm it.':'Consider both trend alignment and nearby levels.'}</p>{c.user_intent.owns_btc&&c.user_intent.entry_price!=null&&c.user_intent.entry_price>0&&<p>Reference-price change from your entry: <strong>{number((c.current_price/c.user_intent.entry_price-1)*100)}%</strong> before fees. This is not realized profit.</p>}<p className="source-note">Closed-candle technical evidence for your selected horizon. Read it alongside the liquidity and sentiment snapshot above. Percentages are evidence shares, not calibrated outcome probabilities.</p></div></RetroWindow>
  <div className="evidence-grid"><RetroWindow title="LEVELS.SR"><ZoneView name="SUPPORT" zone={sr.nearest_support} price={c.current_price}/><ZoneView name="RESISTANCE" zone={sr.nearest_resistance} price={c.current_price}/></RetroWindow>
   <RetroWindow title="MOMENTUM"><div className="big-stat"><strong>{number(m.rsi14,1)}</strong><span>RSI / 14</span></div><Meter value={m.rsi14}/><dl className="stat-list"><div><dt>MACD histogram</dt><dd>{number(m.macd_histogram)}</dd></div><div><dt>EMA20 direction</dt><dd>{m.ema20_slope.toUpperCase()}</dd></div><div><dt>EMA20</dt><dd>{money(m.ema20)}</dd></div><div><dt>EMA50</dt><dd>{money(m.ema50)}</dd></div><div><dt>EMA200</dt><dd>{money(m.ema200)}</dd></div></dl></RetroWindow>
   <RetroWindow title="VOLUME"><div className="big-stat"><strong>{number(v.volume_ratio)}<small>×</small></strong><span>PREVIOUS 20 AVG</span></div><div className="outline-tag">{v.classification.replaceAll('_',' ').toUpperCase()}</div><dl className="stat-list"><div><dt>Taker buy</dt><dd>{v.taker_buy_ratio==null?'—':`${number(v.taker_buy_ratio*100,1)}%`}</dd></div><div><dt>Breakout volume</dt><dd>{c.price_action[tf].volume_confirmed?'CONFIRMED':'UNCONFIRMED'}</dd></div></dl><p className="source-note">Binance BTCUSDT spot only.</p></RetroWindow>
  </div>
  <div className="bottom-grid"><RetroWindow title="TECHNICAL.EVIDENCE"><p className="eyebrow">DETERMINISTIC TECHNICAL EVIDENCE</p><div className="score-grid">{[['BULLISH',ev.bullish_evidence],['BEARISH',ev.bearish_evidence],['UNCERTAIN',ev.uncertain]].map(([label,value])=><div key={label}><span>{label}</span><strong>{number(Number(value),1)}%</strong><Meter value={Number(value)}/></div>)}</div><p>This is a heuristic technical score, not a probability forecast.</p><details><summary>INSPECT SCORE BREAKDOWN</summary><div className="score-details">{Object.entries(ev.breakdown).map(([name,b])=><p key={name}>{name.replaceAll('_',' ')} · weight {number(b.weight*100,0)}% · signed signal {number(b.signal,3)} · bullish {number(b.bullish)} / bearish {number(b.bearish)} / uncertain {number(b.uncertain)}</p>)}</div></details></RetroWindow>
   <RetroWindow title="THESIS.VALIDITY"><span className="eyebrow">CURRENT STRUCTURE VALID WHILE</span><h3>{c.thesis_invalidation.current_structure_valid_while}</h3><span className="eyebrow">WEAKENING CONDITIONS</span>{c.thesis_invalidation.weakening_conditions.length?<ul>{c.thesis_invalidation.weakening_conditions.map(x=><li key={x}>{x}</li>)}</ul>:<p>No directional thesis established.</p>}{c.thesis_invalidation.strong_invalidation && <div className="invalidation"><span>STRONG INVALIDATION</span><strong>{c.thesis_invalidation.strong_invalidation.condition.toUpperCase()}</strong><b>{money(c.thesis_invalidation.strong_invalidation.level)}</b><small>{c.thesis_invalidation.strong_invalidation.structure_condition}</small></div>}</RetroWindow></div>
  <RetroWindow title="VOLATILITY & EVENTS"><div className="volatility-grid"><div><span className="eyebrow">ATR / 14</span><strong>{money(vol.atr14)} <small>({number(vol.atr_percent)}%)</small></strong></div><div><span className="eyebrow">ANNUALIZED HISTORICAL VOLATILITY</span><strong>{number(vol.historical_volatility_annualized_pct)}%</strong><small>30 returns · {vol.classification.toUpperCase()}</small></div><div><span className="eyebrow">LATEST CLOSED-CANDLE EVENTS</span>{c.price_action[tf].events.length?c.price_action[tf].events.map((e,i)=><p key={i}>{e.event.replaceAll('_',' ').toUpperCase()} @ {money(e.level)}</p>):<p>NO CONFIRMED EVENT</p>}</div></div></RetroWindow>
 </div>;
}
