import type { Metadata } from 'next';
import BrandLogo from '@/components/BrandLogo';
import RetroWindow from '@/components/RetroWindow';

export const metadata: Metadata = { title: 'priceactioner — راهنمای استفاده' };
export default function Docs(){return <main className="guide-page"><header className="admin-header"><BrandLogo/><a href="/">← BACK TO WORKSPACE</a></header><RetroWindow title="DOCS / QUICK START" status="USER GUIDE"><article className="guide-body" lang="fa" dir="rtl"><h1>از فرم تا اولین خروجی</h1><p>در priceactioner لازم نیست پرامپت بنویسی. فقط برنامه‌ای را که در نظر داری انتخاب کن؛ نرم‌افزار وضعیت بازار را بررسی می‌کند. انتخاب BUY یا SELL هیچ خریدوفروشی انجام نمی‌دهد.</p>
 <h2>۱. یک مثال برای یادگیری</h2><p>برای دیدن نحوه کار برنامه، این مثال آموزشی را وارد کن؛ این نمونه پیشنهاد خرید نیست:</p><ol><li><bdi>What are you considering?</bdi> ← <bdi>BUY BTC</bdi></li><li><bdi>When do you plan to act?</bdi> ← <bdi>NOW</bdi></li><li><bdi>How long do you plan to hold?</bdi> ← <bdi>7 DAYS</bdi></li><li><bdi>Risk tolerance</bdi> ← <bdi>BALANCED</bdi></li><li><bdi>Priority</bdi> ← <bdi>AVOID A BAD ENTRY</bdi></li><li>اگر بیت‌کوین نداری، گزینه <bdi>I already own BTC</bdi> را تیک نزن.</li><li>دکمه <bdi>ANALYZE BTC</bdi> را بزن و منتظر نتیجه بمان.</li></ol>
 <h2>۲. هر فیلد چه معنی دارد؟</h2><dl className="guide-fields"><div><dt>تصمیمی که بررسی می‌کنی</dt><dd><bdi>BUY BTC</bdi>: خرید را بررسی می‌کنی. <bdi>SELL BTC</bdi>: فروش را بررسی می‌کنی. <bdi>ALREADY OWN BTC</bdi>: بیت‌کوین داری و وضعیت نگهداری را می‌سنجی. <bdi>WAIT FOR ENTRY</bdi>: فعلاً منتظر ورود هستی.</dd></div><div><dt>زمان اقدام</dt><dd>چه زمانی می‌خواهی تصمیم بگیری؟ <bdi>NOW</bdi> یعنی همین حالا؛ <bdi>WITHIN 3 DAYS</bdi> یعنی طی سه روز آینده.</dd></div><div><dt>مدت نگهداری</dt><dd>اگر وارد شوی، حدوداً چند روز می‌خواهی نگه داری؟ این گزینه با زمان اقدام فرق دارد و وزن تایم‌فریم‌ها را تغییر می‌دهد. برای فروش نمایش داده نمی‌شود؛ در آن حالت زمان اقدام مبنای افق تحلیل است.</dd></div><div><dt>ریسک‌پذیری</dt><dd><bdi>CONSERVATIVE</bdi>: محتاط. <bdi>BALANCED</bdi>: متعادل. <bdi>AGGRESSIVE</bdi>: ریسک‌پذیرتر.</dd></div><div><dt>اولویت</dt><dd><bdi>AVOID A BAD ENTRY</bdi>: دوری از ورود نامناسب. <bdi>CATCH TREND EARLY</bdi>: توجه به شروع روند. <bdi>BALANCED</bdi>: تعادل بین این دو.</dd></div><div><dt>مالکیت و قیمت ورود</dt><dd>اگر بیت‌کوین داری، گزینه مالکیت را فعال کن. قیمت ورود اختیاری و برحسب USDT است؛ اگر نمی‌دانی، خالی بگذار. برای <bdi>ALREADY OWN BTC</bdi> مالکیت خودکار فعال می‌شود.</dd></div></dl><p>ریسک، اولویت و قیمت ورود در ورودی ساخته‌شده ذخیره می‌شوند. فعلاً محاسبات واقعی بازار مثل RSI و حمایت را تغییر نمی‌دهند و توصیه شخصی تولید نمی‌کنند.</p>
 <h2>۳. خروجی را چطور بخوانی؟</h2><ul><li><bdi>ANALYSIS.RESULT</bdi>: ساختار فعلی و افق انتخاب‌شده. قیمت مرجع از کندل بسته‌شده می‌آید؛ ممکن است با قیمت لحظه‌ای نمودار فرق داشته باشد.</li><li><bdi>LEVELS.SR</bdi>: محدوده‌های حمایت و مقاومت و امتیاز قدرتشان. اگر داده کافی نباشد، سطحی ساخته نمی‌شود.</li><li><bdi>MOMENTUM / VOLUME / VOLATILITY</bdi>: مومنتوم، حجم و نوسان.</li><li><bdi>TECHNICAL.EVIDENCE</bdi>: جمع شواهد صعودی، نزولی و نامشخص برابر ۱۰۰ است؛ این امتیاز احتمال قطعی آینده نیست.</li><li><bdi>THESIS.VALIDITY</bdi>: شرایطی که ساختار فعلی را تضعیف یا بی‌اعتبار می‌کند.</li></ul>
 <h2>۴. ورودی دقیق چگونه ساخته می‌شود؟</h2><p>بعد از تحلیل، پنجره <bdi>REQUEST.PREVIEW</bdi> را باز کن. چهار نمایش دارد:</p><ol><li><bdi>READABLE</bdi>: خلاصه قابل‌خواندن تحلیل و فرم تو.</li><li><bdi>STATE</bdi>: شیء JSON شامل فرم تو، افق تحلیل و محاسبات Python.</li><li><bdi>QUESTIONS</bdi>: شش سؤال ثابت درباره جهت بازار، تناسب افق، دوام روند، کیفیت شواهد، ریسک و پشتیبانی از برنامه کاربر.</li><li><bdi>FULL REQUEST</bdi>: متن کامل و دقیق JSON ساخته‌شده. <bdi>COPY FULL REQUEST</bdi> همین متن را کپی می‌کند.</li></ol><pre dir="ltr">{`{
  "model": null,
  "state": {
    "user_intent": { "action": "buy", "holding_period_days": 7 },
    "analysis_plan": {
      "primary_timeframe": "4h",
      "timeframe_weights": { "1h": 0.15, "4h": 0.45, "1d": 0.40 }
    }
  },
  "questions": [ ... ]
}`}</pre><p>کد بالا فقط نمایش کوتاه‌شده ساختار است، نه یک درخواست کامل. مقادیر واقعی بازار و تمام فیلدها را در <bdi>FULL REQUEST</bdi> همان تحلیل می‌بینی. اگر مدل تنظیم نشده باشد، مقدار <bdi>model</bdi> برابر <bdi>null</bdi> است. هیچ کلید API در این خروجی نیست.</p><p>در این مرحله فقط ورودی محلی ساخته می‌شود و چیزی به سرویس هوش مصنوعی فرستاده نمی‌شود. سازگاری نهایی این قالب با API زنده هنوز بررسی نشده است.</p>
 <h2>۵. سه درخواست در روز</h2><p>هر کاربر روزانه ۳ تحلیل دارد. فعلاً چون ورود کاربری نداریم، سهمیه با کوکی همان مرورگر محاسبه می‌شود و ساعت ۰۰:۰۰ UTC از نو شروع می‌شود. تعداد باقی‌مانده بالای فرم دیده می‌شود. خطای تحلیل از سهمیه کم نمی‌کند؛ تغییر تایم‌فریم نمودار و باز کردن راهنما هم رایگان است.</p><p>این سقف، شناسایی قطعی هر شخص نیست: مرورگر یا دستگاه دیگر سهمیه جدا دارد و پاک‌کردن کوکی هویت مرورگر را از بین می‌برد.</p>
 <a className="guide-start" href="/">برگشت به فرم و گرفتن اولین خروجی ←</a></article></RetroWindow></main>;}
